# Generated by Django 5.2.3 on 2025-07-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_like',
            name='saved',
        ),
    ]
