export const elements = {
    div:{
        tag:"div",
        style:{height:"40px",background:"red"}
    },
    flex:{
        tag:"div",
        style:{display:"flex",height:"40px",background:"red"}
    },
    grid:{
        tag:"div",
        style:{display:"grid",height:"40px",background:"red"}
    },
    table:{
        tag:"table",
        style:{height:"400px",width:"500px",background:"red", border:"1px solid white"},
        children:[
            {
                tag:"thead",
                children:[
                    {
                        tag:"tr",
                        children:[
                            {tag:"th"},
                            {tag:"th"},
                            {tag:"th"},
                            {tag:"th"},
                        ]
                    }
                ]
            },
            {
                tag:"tbody",
                children:[
                    {
                        tag:"tr",
                        children:[
                            {tag:"td"},
                            {tag:"td"},
                            {tag:"td"},
                            {tag:"td"},
                        ]
                    },
                    {
                        tag:"tr",
                        children:[
                            {tag:"td"},
                            {tag:"td"},
                            {tag:"td"},
                            {tag:"td"},
                        ]
                    },
                    {
                        tag:"tr",
                        children:[
                            {tag:"td"},
                            {tag:"td"},
                            {tag:"td"},
                            {tag:"td"},
                        ]
                    },
                ]
            },
        ]
    },
} 